import Head from "next/head";
import { BackgroundContainer } from "styles/common";

import { useState, useEffect } from "react";

import Intro from "containers/Intro";
import Login from "containers/Login";
import Home from "containers/Home";

import Upper from "foundations/Upper";

export default function Page() {
  const [state, setState] = useState("home");
  const [userName, setUserName] = useState("Cyan");

  useEffect(() => {
    if (state === "intro") {
      const timeout = setTimeout(() => {
        setState("login");
      }, 2500);
      return () => clearTimeout(timeout);
    }
  }, [state]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BackgroundContainer>
        <Intro show={state === "intro"} />
        <Login
          show={state === "login"}
          handleNext={(name) => {
            setUserName(name);
            setState("home");
          }}
        />
        <Home show={state === "home"} userName={userName} />
        {state === "home" && <Upper />}
      </BackgroundContainer>
    </>
  );
}
