import Head from "next/head";
import { BackgroundContainer } from "styles/common";

import { useState, useEffect } from "react";

import Intro from "containers/Intro";
import Login from "containers/Login";

export default function Home() {
  const [showIntro, setShowIntro] = useState(true);

  useEffect(() => {
    const timeout = setTimeout(() => {
      setShowIntro(false);
    }, 2500);
    return () => clearTimeout(timeout);
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BackgroundContainer>
        <Intro show={showIntro} />
        <Login show={!showIntro} />
      </BackgroundContainer>
    </>
  );
}
